[build]
  command = "npm run build && hugo"
  functions = "netlify/functions"
  publish = "_site"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=1604800, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, maxage=4096"
    Content-Security-Policy = "upgrade-insecure-requests"
    Permissions-Policy = "microphone=()"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
